// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoUgS3qAmIzparKeUnkjOxZqouLonq64I',
    appId: '1:415964149260:web:06503c5aa2195c68e1e029',
    messagingSenderId: '415964149260',
    projectId: 'study-app-93cd2',
    authDomain: 'study-app-93cd2.firebaseapp.com',
    storageBucket: 'study-app-93cd2.appspot.com',
    measurementId: 'G-G1EHRREC99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy1DU4H22YEn7tnmdfznOo2BN4xT7EIAI',
    appId: '1:415964149260:android:014e623fdf5ec6e7e1e029',
    messagingSenderId: '415964149260',
    projectId: 'study-app-93cd2',
    storageBucket: 'study-app-93cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3L6JnYEhWj2b20YXEnh4FczYbMUPGWE',
    appId: '1:415964149260:ios:7f17928dcfb55221e1e029',
    messagingSenderId: '415964149260',
    projectId: 'study-app-93cd2',
    storageBucket: 'study-app-93cd2.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe3L6JnYEhWj2b20YXEnh4FczYbMUPGWE',
    appId: '1:415964149260:ios:7f17928dcfb55221e1e029',
    messagingSenderId: '415964149260',
    projectId: 'study-app-93cd2',
    storageBucket: 'study-app-93cd2.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoUgS3qAmIzparKeUnkjOxZqouLonq64I',
    appId: '1:415964149260:web:93b6e9619fe77cf6e1e029',
    messagingSenderId: '415964149260',
    projectId: 'study-app-93cd2',
    authDomain: 'study-app-93cd2.firebaseapp.com',
    storageBucket: 'study-app-93cd2.appspot.com',
    measurementId: 'G-1KG2M7Q64T',
  );
}
